CodeFirst/WebUI/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DBAccess;
using Models;

namespace WebUI.Controllers
{
    public class CategoriesController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Categories
        public ActionResult Index(Guid? id,int pageIndex=1)
        {
            //每页显示的记录数
            var pageSize = 5;

            //查询顶级分类
            var topCategories = db.Categories.Where(n => n.ParentCategory == null).ToList();
            //动态传值到视图
            ViewBag.Tops = topCategories;

            if (id == null)
            {
                //查询出所有的分类
                var list = db.Categories.ToList();
                //计算总数
                var recordCount = list.Count;
                //如果记录为空
                if (recordCount == 0)
                {
                    //当前页
                    ViewBag.PageIndex = 1;
                    //每页的记录数
                    ViewBag.PageSize =pageSize;
                    //所有记录的总数
                    ViewBag.TotalCount = recordCount;
                    return View(list);
                }

                //记录不为0
                //总的页数
                int pageCount = Convert.ToInt32(Math.Ceiling((double) recordCount / pageSize));
                //当前页 不能小于1 不能大于PageCount
                pageIndex = pageIndex < 1 ? 1 : pageIndex;
                pageIndex = pageIndex > pageCount ? pageCount : pageIndex;

                //当前页
                ViewBag.PageIndex = pageIndex;
                //每页的记录数
                ViewBag.PageSize = pageSize;
                //所有记录的总数
                ViewBag.TotalCount = recordCount;

                //提取出当前页的记录
                var pageList = db.Categories.OrderBy(n => n.SortCode).Skip((pageIndex - 1) * pageSize).Take(pageSize)
                    .ToList();
                return View(pageList);
            }
            else
            {
                var list = db.Categories.Where(n => n.ParentCategory.ID == id).OrderBy(n => n.SortCode).ToList();
                //计算总数
                var recordCount = list.Count;
                //如果记录为空
                if (recordCount == 0)
                {
                    //当前页
                    ViewBag.PageIndex = 1;
                    //每页的记录数
                    ViewBag.PageSize = pageSize;
                    //所有记录的总数
                    ViewBag.TotalCount = recordCount;
                    return View(list);
                }
                
                //记录不为0
                //总的页数
                int pageCount = Convert.ToInt32(Math.Ceiling((double)recordCount / pageSize));
                //当前页 不能小于1 不能大于PageCount
                pageIndex = pageIndex < 1 ? 1 : pageIndex;
                pageIndex = pageIndex > pageCount ? pageCount : pageIndex;

                //当前页
                ViewBag.PageIndex = pageIndex;
                //每页的记录数
                ViewBag.PageSize = pageSize;
                //所有记录的总数
                ViewBag.TotalCount = recordCount;

                var data = db.Categories.Where(n => n.ParentCategory.ID == id).OrderBy(n => n.SortCode)
                    .Skip((pageIndex - 1) * pageSize).Take(pageSize).ToList();
                return View(data);
            }
        }

        // GET: Categories/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,SortCode,Name,Dscn")] Category category)
        {
            if (ModelState.IsValid)
            {
                category.ID = Guid.NewGuid();
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,SortCode,Name,Dscn")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CodeFirst/WebUI/Views/Categories/Create.cshtml
@model Models.Category

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SortCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SortCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SortCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dscn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dscn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dscn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CodeFirst/WebUI/Views/Categories/Delete.cshtml
@model Models.Category

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SortCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SortCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dscn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dscn)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CodeFirst/WebUI/Views/Categories/Details.cshtml
@model Models.Category

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SortCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SortCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dscn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dscn)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CodeFirst/WebUI/Views/Categories/Edit.cshtml
@model Models.Category

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.SortCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SortCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SortCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dscn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dscn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dscn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CodeFirst/WebUI/Views/Categories/Index.cshtml
@using DBAccess
@using Models
@using WebUI.Common
@model IEnumerable<Models.Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var tops = ViewBag.Tops as List<Category>;

    //当前页码
    int pageIndex = ViewBag.PageIndex;
    //每页显示的记录数
    int pageSize =  ViewBag.PageSize;
    //总的记录数量
    int totalCount =  ViewBag.TotalCount;
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <ul>
                <li><a href="@Url.Action("index","Categories",new{id=""})">全部</a></li>
                @foreach (var t in tops)
                {
                    <li>@Html.ActionLink(t.Name, "Index", new {id = t.ID})
                        @*生成子分类的菜单*@
                    @CategoryTree.GetTreeMenu(t)
                    </li>
                }
            </ul>
        </div>
        <div class="col-md-9">
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.SortCode)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Dscn)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.SortCode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Dscn)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                            @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                        </td>
                    </tr>
                }

            </table>
            
            <hr/>
            @Html.HtmlPager(pageIndex,index=>Url.Action("index","Categories",new{pageIndex=index}),
                totalCount,pageSize,10)

        </div>
    </div>
</div>